# Generated by Django 3.0.3 on 2020-03-08 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Supplier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OsposItems',
            fields=[
                ('ospossuppliers_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='Supplier.OsposSuppliers')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('item_number', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(max_length=255)),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('reorder_level', models.DecimalField(decimal_places=3, max_digits=15)),
                ('receiving_quantity', models.DecimalField(decimal_places=3, max_digits=15)),
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('pic_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('allow_alt_description', models.IntegerField()),
                ('is_serialized', models.IntegerField()),
                ('stock_type', models.IntegerField()),
                ('item_type', models.IntegerField()),
                ('tax_category_id', models.IntegerField()),
                ('delete', models.IntegerField()),
                ('custom1', models.CharField(blank=True, max_length=255, null=True)),
                ('custom2', models.CharField(blank=True, max_length=255, null=True)),
                ('custom3', models.CharField(blank=True, max_length=255, null=True)),
                ('custom4', models.CharField(blank=True, max_length=255, null=True)),
                ('custom5', models.CharField(blank=True, max_length=255, null=True)),
                ('custom6', models.CharField(blank=True, max_length=255, null=True)),
                ('custom7', models.CharField(blank=True, max_length=255, null=True)),
                ('custom8', models.CharField(blank=True, max_length=255, null=True)),
                ('custom9', models.CharField(blank=True, max_length=255, null=True)),
                ('custom10', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'ospos_items',
                'managed': False,
            },
            bases=('Supplier.ospossuppliers',),
        ),
    ]
