# Generated by Django 3.0.3 on 2020-02-29 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'managed': False},
        ),
    ]
