# Generated by Django 3.0.3 on 2020-02-29 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0002_auto_20200229_1013'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='person',
            table='person',
        ),
    ]
