# Generated by Django 3.0.3 on 2020-03-08 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0003_auto_20200229_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='OsposPeople',
            fields=[
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('gender', models.IntegerField(blank=True, null=True)),
                ('phone_number', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('address_1', models.CharField(max_length=255)),
                ('address_2', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('zip', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('comments', models.TextField()),
                ('person_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'ospos_people',
                'managed': False,
            },
        ),
    ]
