# Generated by Django 3.0.3 on 2020-02-29 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0002_auto_20200229_1013'),
        ('Employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Person.Person')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('deleted', models.IntegerField()),
            ],
            options={
                'db_table': 'employee',
                'managed': False,
            },
            bases=('Person.person',),
        ),
        migrations.DeleteModel(
            name='person',
        ),
    ]
