# Generated by Django 3.0.3 on 2020-03-08 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0004_ospospeople'),
        ('Employee', '0002_auto_20200229_1013'),
    ]

    operations = [
        migrations.CreateModel(
            name='OsposEmployees',
            fields=[
                ('ospospeople_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Person.OsposPeople')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('deleted', models.IntegerField()),
                ('hash_version', models.IntegerField()),
                ('language', models.CharField(blank=True, max_length=48, null=True)),
                ('language_code', models.CharField(blank=True, max_length=8, null=True)),
            ],
            options={
                'db_table': 'ospos_employees',
                'managed': False,
            },
            bases=('Person.ospospeople',),
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
