# Generated by Django 3.0.3 on 2020-03-08 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Person', '0004_ospospeople'),
    ]

    operations = [
        migrations.CreateModel(
            name='OsposSuppliers',
            fields=[
                ('ospospeople_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Person.OsposPeople')),
                ('company_name', models.CharField(max_length=255)),
                ('agency_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('deleted', models.IntegerField()),
            ],
            options={
                'db_table': 'ospos_suppliers',
                'managed': False,
            },
            bases=('Person.ospospeople',),
        ),
    ]
